# @package _global_
# Locomotion environment configuration optimized for soil terrain training
# Based on locomotion.yaml but with conservative command ranges and soil-specific termination

defaults:
  - legged_base

# Env structure
env:
  _target_: humanoidverse.envs.locomotion.locomotion.LeggedRobotLocomotion
  config:
    max_episode_length_s: 20
    locomotion_obs_scales:
      lin_vel: 1.0
      ang_vel: 1.0
      dof_pos: 1.0
      dof_vel: 1.0
      humanoid_commands_scale: 1.0
    
    # CONSERVATIVE command ranges for soil training (Stage 1 curriculum)
    locomotion_command_ranges:
      lin_vel_x: [-0.3, 0.3]  # Reduced from [-1.0, 1.0] for stable soil learning
      lin_vel_y: [-0.3, 0.3]  # Reduced from [-1.0, 1.0] for stable soil learning  
      ang_vel_yaw: [-0.3, 0.3]  # Reduced from [-1.0, 1.0] for stable soil learning
      heading: [-3.14, 3.14]
    locomotion_command_resampling_time: 15.0  # Increased from 10.0 for more stable learning

    # SOIL-SPECIFIC termination conditions
    termination:
      terminate_by_contact: False # problematic in isaacgym when g1+terrain
      # terminate_by_lin_vel: False
      # terminate_by_ang_vel: False
      terminate_by_gravity: True
      terminate_by_low_height: True  # ENABLED to prevent excessive soil sinkage

    termination_scales:
      termination_min_base_height : 0.4  # Increased from 0.3 to account for soil settling
      # termination_max_base_vel : 10.0
      # termination_max_base_ang_vel : 5.0
      termination_gravity_x : 0.8
      termination_gravity_y : 0.8
      


# Globally accessible parameters
log_task_name: locomotion

eval_overrides:
  env:
    config: 
      max_episode_length_s: 100000