# @package _global_

defaults:
  - domain_rand_base

domain_rand:
  # Wet/loose soil friction window
  randomize_friction: True
  friction_range: [0.30, 0.50]

  # Disturbances
  push_robots: True
  push_force_N: 50
  push_duration_s_range: [0.12, 0.20]
  push_interval_s: [4, 8]

  # Widen robot DR for robustness
  randomize_base_com: True
  base_com_range:
    x: [-0.15, 0.15]
    y: [-0.15, 0.15]
    z: [-0.15, 0.15]

