# @package _global_
# Soil-specific domain randomization configuration
# Includes terrain property variations to simulate different soil moisture and compaction states

defaults:
  - domain_rand_base  # inherit base randomization settings

domain_rand:
  # Soil-specific terrain property randomization
  randomize_terrain_properties: True
  
  # Soil friction randomization (varies with moisture content)
  # Dry sandy loam: μ ≈ 0.65, wet clay loam: μ ≈ 0.50
  terrain_friction_range: [0.50, 0.70]
  
  # Soil cohesion randomization (varies significantly with water content)
  # Range: 5-15 kPa as mentioned in audit
  terrain_cohesion_range: [5000, 15000]  # Pa
  
  # Terrain roughness/amplitude randomization for varied furrow depth
  terrain_amplitude_range: [0.010, 0.020]  # 1-2 cm variation in furrow depth
  
  # Enhanced robot parameter randomization for soil robustness
  
  # Push disturbances (more aggressive for soil terrain)
  push_robots: True
  push_interval_s: [4, 8]  # More frequent pushes to test stability
  max_push_vel_xy: 0.4     # Slightly higher push forces
  
  # Base COM randomization (center of mass shifts)
  randomize_base_com: True
  base_com_range:
    x: [-0.12, 0.12]       # Slightly increased for soil uncertainty
    y: [-0.12, 0.12]
    z: [-0.12, 0.12]
  
  # Link mass randomization (payload variation)
  randomize_link_mass: True
  link_mass_range: [0.75, 1.3]  # Wider range for robustness
  
  # PD gain randomization (actuator variations)
  randomize_pd_gain: True
  kp_range: [0.7, 1.3]     # Wider range for soil compliance
  kd_range: [0.7, 1.3]
  
  # Base friction with ground (robot's own friction, separate from terrain)
  randomize_friction: True
  friction_range: [0.4, 1.4]  # Wider range for varied surface conditions
  
  # Torque RFI (actuator noise)
  randomize_torque_rfi: True
  rfi_lim: 0.12            # Slightly higher noise for realism
  randomize_rfi_lim: True
  rfi_lim_range: [0.4, 1.6]
  
  # Control delay randomization
  randomize_ctrl_delay: True
  ctrl_delay_step_range: [0, 3]  # Up to 3 steps delay (135ms at 50Hz)
  
  # Additional soil-specific randomization
  
  # Gravity variations (simulates inclined terrain or load changes)
  randomize_gravity: True
  gravity_range: [9.5, 10.3]  # ±4% variation
  
  # Joint limits randomization (wear/calibration drift)
  randomize_joint_limits: True
  joint_limit_range: [0.95, 1.0]  # Slight reduction in available range
